name: React Native CD

on:
  push:
    branches:
      - main

jobs:
  deploy_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ğŸ›’
        uses: actions/checkout@v2

      - name: Set up Ruby ğŸ’
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Fastlane ğŸï¸
        run: gem install fastlane

      - name: iOS Beta Deployment ğŸ–¥ï¸âœˆï¸
        run: fastlane ios beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

      - name: Android Beta Deployment ğŸ¤–âœˆï¸
        run: fastlane android beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
