# TODO: Use bundle exec for fastlane and gemfile
name: React Native CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout_and_setup:
    name: "Setup: Installing dependencies ğŸ›’"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ğŸ›’
        uses: actions/checkout@v2

      - name: Set up Ruby ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Fastlane ğŸï¸
        run: gem install fastlane

  ios_beta_deploy:
    name: "Deployment: Deploying iOS Beta ğŸ–¥ï¸âœˆï¸"
    needs: checkout_and_setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ğŸ›’
        uses: actions/checkout@v2

      # Repeat the setup steps, including restoring the cache
      - name: Set up Ruby ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: iOS Beta Deployment ğŸ–¥ï¸âœˆï¸
        run: fastlane ios beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  android_beta_deploy:
    name: "Deployment: Deploying Android Beta ğŸ¤–âœˆï¸"
    needs: checkout_and_setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ğŸ›’
        uses: actions/checkout@v2

      # Repeat the setup steps, including restoring the cache
      - name: Set up Ruby ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Android Beta Deployment ğŸ¤–âœˆï¸
        run: fastlane android beta
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          JSON_KEY_DATA: ${{ secrets.JSON_KEY_DATA }}
